### ISSUE TITLE
double // in url

### ISSUE THREAD

**Issue by wincepinter** [KindleModding/KWebBrew#1]
Hi,
I accidentally entered the wrong url and it couldn't list the installed apps.
file:///mnt/us/kwebbrew//index.html

 getDirectory("../apps/").then(function (data) 

Best regards,
Vince Pinter

**Comment by ThatHackerDudeFromCyberspace** [comment]
Can you please send a screenshot of the log?
You can screenshot a Kindle by tapping on two opposite corners at the same time, when you connect it to a computer they will appear on the Kindle's drive, after that you can attach it to a comment

Also, does it work if you use the provided bookmark (go to bookmarks and scroll to the bottom)

**Comment by ThatHackerDudeFromCyberspace** [comment]
Wait, I think I see what went wrong, yeah, I would recommend you just type the path in correctly as you can just type a new path in the browser, or use a bookmark, but I'll fix this in the next release

**Comment by ThatHackerDudeFromCyberspace** [comment]
Fixed in [v1.2.0](https://github.com/KindleModding/KWebBrew/releases/tag/v1.2.0)
