### ISSUE TITLE
No Longer Works On Firmware > 5.16.3

### ISSUE THREAD

**Issue by ry10hu** [KindleModding/KWebBrew#5]
The Updated Web Browser Seems To Have Messed With/Disabled The file:/// Protocol.

**Comment by Aityz** [comment]
Yeah, I noticed that too, no real way to fix it, there is a possibility that we could have, like a Github pages hosted KWebBrew instance, but that would require internet instead.

**Comment by ry10hu** [comment]
Aye, Although If I Remember Correctly, Can't You Edit The Kindle Store HTML?
Or Was That Patched/Never Existed

**Comment by Aityz** [comment]
I believe that it was patched recently, they no longer cache the store on the device iirc.

**Comment by Bob-Teh777** [comment]
> I believe that it was patched recently, they no longer cache the store on the device iirc.

I just tested, and they still do cache it! I have a Kindle Paperwhite 11th gen, And I managed to edit the Kindle Store HTML!
From what I tested, They Store it in `\.active_content_sandbox\store\resource\cachedResources` when accesing from USB.

I am on Latest Software, `5.16.9`
I'm currently playing around with the Store's HTML, But it gets reset on every restart.

**Note: I managed to get the store to show "Hi!" On The top of the screen!**

**Comment by Bob-Teh777** [comment]
Screenshot On Kindle (No Jailbreak)
![screenshot_2024_07_07T11_23_07+1200](https://github.com/KindleModding/KWebBrew/assets/114314463/42d368ba-94b7-4e84-8296-12ce016367a5)

**Comment by ry10hu** [comment]
By restart you mean full reboot right? E.g. holding the power button > restart. Not just turning the screen off and on.

Edit: Registered my Kindle and tried to find the folder you mentioned but could not, however _I did find_ an sqlite DB that has some html in it. (haven't analyzed it very well yet, found some images)

This is all on 5.16.9 (4246250033) btw.

And if we were to continue this discussion, it would probably be best not to do so in an old issue.

**Comment by Bob-Teh777** [comment]
EDIT: Yes, full reboot is the correct term

Yeah, I remember that before 5.16.3, I couldn't find any of this stuff, just appeared after KWebBrew stopped working.
I did find an old project called [Mequito](https://github.com/KindleModding/Mesquito), so I took some code and and imported it into my Kindle, and it worked! You should Maybe try opening the store a couple times, if not, try making the folder. Then again, I've been playing around with the inner files (Only Accesible via USB, not root or jail-broken). Although, Mesquito's github README does say that it doesn't work for some higher versions... Also, I should maybe make a new issue or repository for this stuff, I don't really know.

> Edit: Registered my Kindle and tried to find the folder you mentioned but could not, however _I did find_ an sqlite DB that has some html in it. (haven't analyzed it very well yet, found some images)

Maybe it's the bookmarks SQLITE DB, what's it's name?

EDIT 2 || Image / Proof:
![screenshot_2024_08_03T11_05_08+1200](https://github.com/user-attachments/assets/9d7b9362-8264-45e2-ba8d-a368b21cbd26)

**Comment by ry10hu** [comment]
Can't remember the name of it, but the extension was .localstorage.

I inspected it a bit, and found out it had the Kindle Store html, upon further investigation I found that changes made to it lasted beyond resets, instead of being reset each time, as editing the cached files did.

Mesquito also seems interesting, will check it out.
